### ISSUE TITLE
Cursor is invisible in Math Blocks

### ISSUE THREAD

**Issue by danielcs88** [adrian-fuertes/typora-notion-theme#10]
Thank you for the beautiful theme. The only annoyance is that the cursor is not visible inside Math blocks.

![Notion Math](https://user-images.githubusercontent.com/13838845/161369976-501ee157-f178-4ad2-8466-779363b94e93.gif)

**Comment by danielcs88** [comment]
I don't know any CSS but from fiddling around, I was able to fix it by simply appending:

```css
.CodeMirror.cm-s-typora-default div.CodeMirror-cursor {
    border-left: 3px solid var(--text-color);
}
```
