### ISSUE TITLE
In Notion Darker Classic, cursor color in code block is not "overridden"

### ISSUE THREAD

**Issue by BrainCrumbz** [adrian-fuertes/typora-notion-theme#17]
We're on Typora for Windows and when using Notion Darker Classic theme, the cursor color in code blocks stays dark/black.

We've checked in theme file and found this style definition:

```css
.CodeMirror.cm-s-typora-default div.CodeMirror-cursor {
    border-left: 2px solid var(--text-color);
}
```

but for some reason (due to CSS rule specificity?) that style is not sensed by the rendering engine:

![immagine](https://user-images.githubusercontent.com/3185573/194606741-a512df40-8587-4655-aa18-5a8dfd41fda3.png)

After playing with the Typora developer tools, we found that the actual CSS selector used by Typora is:

```css
.CodeMirror div.CodeMirror-cursor
```

![immagine](https://user-images.githubusercontent.com/3185573/194608440-7e345fa7-9841-4306-9e7d-d9d2fbcaa393.png)

We opened a custom user `notion-darker-classic.user.css` by combining the two:

```css
.CodeMirror div.CodeMirror-cursor {
  border-left: 2px solid var(--text-color);
}
```

and now the cursor is actually white and thicker:

![immagine](https://user-images.githubusercontent.com/3185573/194606268-8b4f07e8-eb5c-4bd4-af83-836520b7b673.png)

HTH
